// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqetvuyuqkanyeiskgwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxZXR2dXl1cWthbnllaXNrZ3duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNDg2MDEsImV4cCI6MjA2MzcyNDYwMX0.fPgS4jamaEGmDF7RUdYmjSv8FVfCNE_dylTOEvSwQhM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);